export default class ProductstoreService {
    data = [
        {
            id: 1,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 2,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 3,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 4,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 5,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 6,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  7,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id:  8,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id:  9,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  10,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 11,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 12,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 13,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 14,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 15,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 16,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 17,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 18,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 19,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 20,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  21,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id:  22,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id: 23,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  24,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 25,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 26,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 27,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 28,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 29,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 30,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 31,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 32,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 33,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 34,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  35,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id:  36,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id:  37,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  38,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 39,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 40,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 41,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 42,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 43,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 44,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 45,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 46,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 47,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 48,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  49,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id:  50,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id:  51,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  52,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 53,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 54,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 55,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 56,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 57,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 58,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 59,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 60,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 61,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 62,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  63,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id: 64,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id: 65,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  66,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 67,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 68,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 69,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 70,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 71,
            title: '4G180',
            details: 'Tenda 4G LTE 150Mbps Mobile WiFi Router | 4G180',
            category: 'Роутер',
            price: 952.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G180.jpg',
            quantity: 20,
        },
        {
            id: 72,
            title: '4G680',
            details: 'Tenda 4G LTE 300Mbps WiFi Router | 4G680',
            category: 'Роутер',
            price: 1252.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/4G680.jpg',
            quantity: 11,
        },
        {
            id: 73,
            title: 'ACB-AC',
            details: 'Ubiquiti AirCube AC WiFi Router | ACB-AC',
            category: 'Роутер',
            price: 1282.61,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-AC.jpg',
            quantity: 19,
        },
        {
            id: 74,
            title: 'ACB-ISP',
            details: 'Ubiquiti AirCube WiFi PoE Access Point with UNMS | ACB-ISP0',
            category: 'Роутер',
            price: 478.26,
            coverImage: 'https://scoop.co.za/download/marketing/images/ACB-ISP.jpg',
            quantity: 3
        },
        {
            id: 75,
            title: 'AF-11FX',
            details: 'Ubiquiti AirFiberX 11GHz PtP Radio | AF-11FX',
            category: 'Роутер',
            price: 10691.3,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FX.jpg',
            quantity: 2,
        },
        {
            id: 76,
            title: 'AF-11FX-DUP-L',
            details: 'Ubiquiti AirFiberX 11Ghz Low Band Duplexer | AF-11FX-DUP-L',
            category: 'Роутер',
            price: 3300,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11FXDUPL.jpg',
            quantity: 6,
        },
        {
            id:  77,
            title: 'AF-11G35',
            details: 'Ubiquiti AirFiber Dish 11Ghz 35dBi 81cm | AF-11G35',
            category: 'Спутниковая тарелка',
            price: 6652.17,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-11G35.jpg',
            quantity: 92,
        },
        {
            id:  78,
            title: 'AF-5XHD',
            details: 'Ubiquiti AirFiber5X HD PtP Radio Gigabit WiFi | AF-5XHD',
            category: 'Роутер',
            price: 6865.22,
            coverImage: 'https://scoop.co.za/download/marketing/images/AF-5XHD.jpg',
            quantity: 121,
        },
        {
            id:  79,
            title: 'AFI-INS',
            details: 'Ubiquiti AmpliFi Instant Router +1 MeshPoint Kit | AFI-INS',
            category: 'Роутер',
            price: 3126.09,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSK.jpg',
            quantity: 61,
        },
        {
            id:  80,
            title: 'AFI-INS-R',
            details: 'Ubiquiti AmpliFi Instant Router | AFI-INS-R',
            category: 'Роутер',
            price: 1717.39,
            coverImage: 'https://scoop.co.za/download/marketing/images/AFI-INSR.jpg',
            quantity: 23,
        },
        {
            id: 81,
            title: 'AF-5G23-S45',
            details: 'Ubiquiti 5GHz AirFiber Dish 23dBi Slant 45 PtP | AF-5G23-S45',
            category: 'Спутниковая тарелка',
            price: 1450,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D523X.jpg',
            quantity: 85,
        },
        {
            id: 82,
            title: 'RD-5G30',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Backhaul PtP | RD-5G30',
            category: 'Спутниковая тарелка',
            price: 2304.35,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530.jpg',
            quantity: 81,
        },
        {
            id: 83,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 1734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },
        {
            id: 84,
            title: 'RD-5G30-LW',
            details: 'Ubiquiti 5GHz AirMax Dish 30dBi Light Weight PtP | RD-5G30-LW',
            category: 'Спутниковая тарелка',
            price: 4734.78,
            coverImage: 'https://scoop.co.za/download/marketing/images/AIR-D530LW.jpg',
            quantity: 231,
        },

    ]
    getProduct(){
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(this.data)

            }, 700);
        });
    }
}